[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "livealleudocs"
authors = [{name = "Terracom", email = "info@liveall.eu"}]
dynamic = ["version", "description"]
